### ISSUE TITLE
Убрать комментарии

### ISSUE THREAD

**Issue by coursar** [AnastasiaBezb/03_homework_bonus_sportmaster#1]
https://github.com/AnastasiaBezb/03_homework_bonus_sportmaster/blob/1aa9a7c42edad6acd7487fd822fa29275e1b0344/app/lib.py#L2-L13

**Comment by AnastasiaBezb** [comment]
https://github.com/AnastasiaBezb/03_homework_bonus_sportmaster/blob/ed6763841e8fc34a4ce1d1a8583ac91702110d0c/app/lib.py#L1-L15 удалила комментарии, тест не проходит, т.к. покрытие не 100%

**Comment by coursar** [comment]
Посмотрите, что не покрывается и покройте.
