### ISSUE TITLE
Вынести current_buy // limit (иначе дублируется три раза)

### ISSUE THREAD

**Issue by coursar** [AnastasiaBezb/03_homework_bonus_sportmaster#4]
https://github.com/AnastasiaBezb/03_homework_bonus_sportmaster/blob/b56012fe4945af3cb771862e1106db1f9f40edd0/app/lib.py#L17

**Comment by AnastasiaBezb** [comment]
https://github.com/AnastasiaBezb/03_homework_bonus_sportmaster/blob/d5a7dcf25d7d98c22d96ca91d68009bd3df40005/app/lib.py#L16-L28

**Comment by coursar** [comment]
Зачем на меня назначать, если сделали - закрывайте сообщением в коммите

**Comment by AnastasiaBezb** [comment]
Т.е. я исправляю код, делаю коммит с сообщением что исправлено, затем кидаю в issue ссылку на код? Или что-то не так?

**Comment by coursar** [comment]
Нет, вы когда делает коммит, в сообщении коммита пишете "fixes #4 Дальше текст сообщения". Подстрока "fixes #4" автоматически закрывает issue с id = 4.

**Comment by coursar** [comment]
issue закроется после того, как вы сделаете push

**Comment by AnastasiaBezb** [comment]
Поняла, спасибо!
