### ISSUE TITLE
(previous_buy // limit) дублируется три раза

### ISSUE THREAD

**Issue by coursar** [AnastasiaBezb/03_homework_bonus_sportmaster#5]
https://github.com/AnastasiaBezb/03_homework_bonus_sportmaster/blob/134a50dddd051f301e46215b212be03485e3655e/app/lib.py#L16-L20

**Comment by AnastasiaBezb** [comment]
https://github.com/AnastasiaBezb/03_homework_bonus_sportmaster/blob/b5d3cf477140a83081e8714773bf1226ded5faa7/app/lib.py#L17-L29
